### ISSUE TITLE
专家的图片

### ISSUE THREAD

**Issue by moesoha** [moesoha/evol-card-guide#1]
专家并没有图片丢上图鉴，不知道是之前写的那个unity unpacker的锅还是啥，颜色不正常。而且就算颜色正常也不知道该怎么处理这类游戏素材图片，对这方面不是很懂，大概需要大佬帮忙。

![snipaste_2018-01-29_00-14-01](https://user-images.githubusercontent.com/5895757/35484317-600383f6-0489-11e8-84f5-aa290a7b66d0.png)

**Comment by kyorin11** [comment]
分解了一下通道，是通道顺序的问题，RGBA正确对应是ABGR，我用matlab把通道交换过来就正常了
![i](https://user-images.githubusercontent.com/36062789/35716718-99668dca-0815-11e8-9a55-6ca25edb2ffb.png)
希望能帮到大佬，自己尝试学习解包，解到最后不知道怎么调用那个.so库没有做下去了……

**Comment by moesoha** [comment]
@kyorin11 感谢。看起来的确是这样。这个对应的 `TextureFormat` 是 `13`，这个格式是交由 [HearthSim/UnityPack](https://github.com/HearthSim/UnityPack) 处理的，我会接着检查尝试修复这个问题。

**Comment by moesoha** [comment]
![snipaste_2018-02-02_13-44-09](https://user-images.githubusercontent.com/5895757/35718379-3388399a-081f-11e8-8004-f5f74073b74f.png)

在 UnityPack 代码中加入了对 `RGBA4444` 这个类型进行的通道交换后颜色正常了。

因为此前没有接触过这类问题，不清楚是 Unity 这个格式本身就是这样子定义的，还是只有这个游戏是这样。（我感觉应该是 Unity 里 RGBA 的通道顺序本来就是 ABGR）这个问题我会提到 UnityPack 的 issue 里。看看国外的 dalao 怎么说。

再次感谢您提供的信息！@kyorin11
